version: '3.8'
services:
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-primary-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    command: ["mongod", "--replSet", "${REPLICA_SET_NAME}", "--port", "27017"]
    networks:
      - mongo-network

  mongo-secondary:
    image: mongo:latest
    container_name: mongo-secondary
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-secondary-data:/data/db
    command: ["mongod", "--replSet", "${REPLICA_SET_NAME}", "--port", "27018"]
    networks:
      - mongo-network

  mongo-arbiter:
    image: mongo:latest
    container_name: mongo-arbiter
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    command: ["mongod", "--replSet", "${REPLICA_SET_NAME}", "--port", "27019"]
    networks:
      - mongo-network

volumes:
  mongo-primary-data:
  mongo-secondary-data:

networks:
  mongo-network:
    driver: bridge
